name: Release

on:
  workflow_dispatch:

jobs:
  changelog:
    name: Update Changelog and Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.update.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Changelog and Version
        id: update
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: "chore(release): :bookmark: {version}"
          git-user-name: "github-actions[bot]"
          git-user-email: "41898282+github-actions[bot]@users.noreply.github.com"
          preset: "conventionalcommits"
          input-file: "CHANGELOG.md"
          skip-ci: false

  build:
    needs: changelog
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build
        run: yarn build

      - name: Release on NPM
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          tag_name: ${{ needs.changelog.outputs.version }}
          name: ${{ needs.changelog.outputs.version }}
          generate_release_notes: true
          make_latest: true
